# Generated by Django 4.2.7 on 2026-05-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('age_group', models.CharField(blank=True, choices=[('Under 18', 'Under 18'), ('18-24', '18-24'), ('25-34', '25-34'), ('35-44', '35-44'), ('45-54', '45-54'), ('55+', '55+')], max_length=20)),
                ('satisfaction', models.PositiveSmallIntegerField()),
                ('likes', models.JSONField(blank=True, default=list)),
                ('comments', models.TextField(blank=True)),
                ('contact_me', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
