# Generated by Django 5.2.14 on 2026-05-21 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_form_surveyresponse_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('short_text', 'Short text'), ('long_text', 'Long text (paragraph)'), ('email', 'Email'), ('phone', 'Phone'), ('number', 'Number'), ('rating', 'Rating (stars)'), ('multiple_choice', 'Multiple choice (pick one)'), ('checkboxes', 'Checkboxes (pick many)'), ('dropdown', 'Dropdown'), ('date', 'Date'), ('time', 'Time'), ('file', 'File upload')], max_length=20)),
                ('label', models.CharField(max_length=200)),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='survey.form')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='survey.form')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='responses/%Y/%m/')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.field')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.response')),
            ],
            options={
                'ordering': ['field__order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='SurveyResponse',
        ),
    ]
